name: 'ECS Deployment'
description: 'Github action to deploy services to ECS'
inputs:
  environment:
    description: 'Stage Environment'
    required: true
  version:
    description: 'Docker image version'
    required: true
  clusterName:
    description: 'ECS cluster name'
    required: true
  serviceName:
    description: 'Service name'
    required: true
  desiredCount:
    description: 'Number of services to deploy'
    required: false
    default: 1
  ecrRegistry:
    description: 'ECR registry name'
    required: true
  taskDefinitionPath:
    description: 'Relative path of task definition js file'
    required: true
    default: 'taskdefinition.js'
  imageName:
    description: 'Name of docker image'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'